### ISSUE TITLE
F-Droid Release

### ISSUE THREAD

**Issue by 6543** [ChickenHook/BinderFuzzy#3]
-> https://gitlab.com/fdroid/rfp/-/issues/1378

**Comment by 6543** [comment]
@SarotecK would be nice if the current master could be tagged :)

EDIT: PS: semantik versioning is nice :)

**Comment by SarotecK** [comment]
Hy,
@6543 tagged, this should match semantic release version style and is compatible to f-droid isn't it?

**Comment by 6543** [comment]
It is :) I'll create a MR for F-Droid ...

**Comment by 6543** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7346

**Comment by IzzySoft** [comment]
Could you please also attach the APK to the current tag – so until the app is listed at "F-Droid proper", it can stay updated [in my repo](https://apt.izzysoft.de/fdroid/index/apk/org.chickenhook.binderfuzzy)?

Apart from that: please decide for a tag name pattern you want to stick to, or updates at F-Droid won't work. Currently, each tag follows a different pattern: first `<versionName>`, then `<versionCode>`, now `v<versionName>`. The last one is fine if you keep it :wink:

**Comment by 6543** [comment]
@SarotecK would be nice if you have a look at https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7346#note_427766960 :)

**Comment by 6543** [comment]
merged: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8061

https://f-droid.org/de/packages/org.chickenhook.binderfuzzy/

closing ...
